title: YFP Credit Evaluation Docs
description: System specification and architecture for YFP Credit Evaluation
# Built-in GitHub Pages theme
theme: jekyll-theme-cayman

# Ensure GFM-style Markdown is parsed correctly
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  smart_quotes: ["apos", "apos", "quot", "quot"]
  typographic_symbols:
    mdash: ---
    ndash: --

# Optional toggles supported by some themes
show_downloads: false

# No plugin changes required; theme is a built-in GitHub Pages theme

# Add meta robots to discourage indexing (not access control)
defaults:
  - scope:
      path: ""
    values:
      robots: noindex, nofollow
